# Cluster modular groups
This is a manual of [cluster_modular_group.sage](https://github.com/kmtm0723/ClusterModularGroup).

A *cluster modular group* is a symmetry group of a *cluster algebra*, which is generated by *mutation loops*.

AUTHOR:
- Shunsuke Kano

REFERENCES:
- [[IK19]](https://arxiv.org/abs/1911.07587)

To use this file, you have to load it first:

In [154]:
load('cluster_modular_group.sage')

This file consists of following classes:

- [**SeedPattern**](#SeedPattern)
- [**SignCone**](#SignCone)
- [**SignFan**](#SignFan)
- [**MutationLoop**](#MutationLoop)

We note that the classes SignFan and MutationLoop are the subclass of the class SeedPattern.

Maybe you will use [MutationLoop](#MutationLoop) mainly, so we recommend to read the usage of it first.

## SeedPattern
A *seed pattern* is an assignment of *seed datum* on each vertex of a given regular tree $\mathbb{T}_N$ such that each adjacent seed data are related by *mutation*.

In this file, the seed pattern is a restricted assignment to a edge path in the regular tree.
That is, for a vertex $t_0 \in \mathbb{T}_N$, we assign a seed datum associated to a given exchange matrix $B_0$.
If next we [mutate](#mutate(k)) at $k_0$ this seed datum, then we assign a new seed datum associated to a mutated exchange matrix $\mu_{k_0}B_0$ to a adjucent vertex $t_1$.
When iterate $h$ times this process, we finally obtain the seed assginment for an edge path $t_0 \overset{k_0}{-\!\!\!-\!\!\!-} t_1 \overset{k_1}{-\!\!\!-\!\!\!-} \cdots \overset{k_{h-1}}{-\!\!\!-\!\!\!-} t_h$.

The class object of SeedPattern storage the exchange matrix assigned to the ending vertex of the edge path and seeds assigned to other vertices as a [*trace*](#trace(t)) of it.
Namely, the mutated object is the seed 

### *class*  SeedPattern(B, D=None)

The *seed pattern* associated to an *exchange matrix*.

INPUT:
- ``B`` -- a skew-symmetric or skew-symmetrizable matrix.
- ``D`` -- (default: ``None``); a symmetrizer of ``B``; a diagonal matrix with positive integers such that ``B*D`` is skew-symmetric.

EXAMPLES:

In [2]:
B = matrix([
    [0,2],
    [-1,0]
])
D = matrix.diagonal([2,1])
S = SeedPattern(B, D)
S

In [3]:
B_4_sph = matrix.zero(6)
B_4_sph[0,2]=1
B_4_sph[2,3]=1
B_4_sph[3,1]=1
B_4_sph[1,0]=1
B_4_sph[3,5]=1
B_4_sph[5,0]=1
B_4_sph[0,4]=1
B_4_sph[4,3]=1
B_4_sph = -B_4_sph + B_4_sph.transpose()
B_4_sph
S_4_sph = SeedPattern(B_4_sph)
S_4_sph.b_matrix()

[ 0  1 -1  0 -1  1]
[-1  0  0  1  0  0]
[ 1  0  0 -1  0  0]
[ 0 -1  1  0  1 -1]
[ 1  0  0 -1  0  0]
[-1  0  0  1  0  0]

In [4]:
S_4_sph.mutate(0)
S_4_sph.b_matrix()

[ 0 -1  1  0  1 -1]
[ 1  0 -1  1 -1  0]
[-1  1  0 -1  0  1]
[ 0 -1  1  0  1 -1]
[-1  1  0 -1  0  1]
[ 1  0 -1  1 -1  0]

In [5]:
S_4_sph.trace(0).b_matrix() == B_4_sph

True

### b_matrix()
Retrun the copy of the exchange matrix of a seed assigned to ending vertex of ``self``.

EXAMPLES:

In [6]:
B_4_sph = matrix.zero(6)
B_4_sph[0,2]=1
B_4_sph[2,3]=1
B_4_sph[3,1]=1
B_4_sph[1,0]=1
B_4_sph[3,5]=1
B_4_sph[5,0]=1
B_4_sph[0,4]=1
B_4_sph[4,3]=1
B_4_sph = -B_4_sph + B_4_sph.transpose()
B_4_sph
S_4_sph = SeedPattern(B_4_sph)

In [7]:
S_4_sph.b_matrix()

[ 0  1 -1  0 -1  1]
[-1  0  0  1  0  0]
[ 1  0  0 -1  0  0]
[ 0 -1  1  0  1 -1]
[ 1  0  0 -1  0  0]
[-1  0  0  1  0  0]

In [8]:
S_4_sph.mutate(0)
S_4_sph.b_matrix()

[ 0 -1  1  0  1 -1]
[ 1  0 -1  1 -1  0]
[-1  1  0 -1  0  1]
[ 0 -1  1  0  1 -1]
[-1  1  0 -1  0  1]
[ 1  0 -1  1 -1  0]

### E(k, e, t=-1)
Return the presentation matrix of dual seed mutation in a direction toward ``k`` of sign = ``e`` at ``t``.

INPUT:
- ``k`` -- a direction of mutation.
- ``e`` -- a sign of a seed mutation.
- ``t`` -- (default -1); if -1, return the presentation matrix at ``self``, otherwise at ``self.trace(t)``.

EXAMPLES:

In [9]:
B = matrix([
    [0,2],
    [-1,0]
])
D = matrix.diagonal([2,1])
S = SeedPattern(B, D)

In [10]:
S.mutate(0)
S.mutate(1)

In [11]:
S.E(0, 1)

[-1  0]
[ 0  1]

In [12]:
S.E(0, 1, t=1)

[-1  0]
[ 2  1]

### E_check(k, e, t=-1)
Return the presentation matrix of seed mutation in a direction toward ``k`` of sign = ``e`` at ``t``.

INPUT:
- ``k`` -- a direction of the mutation.
- ``e`` -- a sign of a seed mutation.
- ``t`` -- (default -1); if -1, return the presentation matrix at ``self``, otherwise return the presentation matrix at ``self.trace(t)``.

EXAMPLES:

In [13]:
B = matrix([
    [0,2,0],
    [-1,0,1],
    [0,-1,0]
])
D = matrix.diagonal([2,1,1])
S = SeedPattern(B, D)

In [14]:
S.mutate(0)
S.mutate(2)

In [15]:
S.E_check(1, -1)

[ 1  0  0]
[ 2 -1  0]
[ 0  0  1]

In [16]:
S.E_check(1, -1, t=0)

[ 1  0  0]
[ 0 -1  1]
[ 0  0  1]

### mutate(k)
Storage the copy of ``self`` to its trace and mutate ``self`` in a direction toward ``k``.

INPUT:
- ``k`` -- a direction of the mutation.

EXAMPLES:

In [17]:
B = matrix([
    [0,3],
    [-1,0]
])
D = matrix.diagonal([3,1])
S = SeedPattern(B, D)

In [18]:
S.mutate(1)
S.mutate(0)
S.mutate(1)

In [19]:
S.trace(0).b_matrix(), S.trace(1).b_matrix(), S.trace(2).b_matrix(), S.b_matrix()

(
[ 0  3]  [ 0 -3]  [ 0  3]  [ 0 -3]
[-1  0], [ 1  0], [-1  0], [ 1  0]
)

### rank()
Return the size of the index set of ``self``.

EXAMPLES:

In [20]:
B = matrix([
    [0,2],
    [-1,0]
])
D = matrix.diagonal([2,1])
S = SeedPattern(B, D)

In [21]:
S.rank()

2

In [22]:
B = matrix([
    [0,2,0],
    [-1,0,1],
    [0,-1,0]
])
D = matrix.diagonal([2,1,1])
S = SeedPattern(B, D)

In [23]:
S.rank()

3

### trace(t)
If ``self`` is the seed pattern on the path $t_0 \overset{k_0}{-\!\!\!-\!\!\!-} t_1 \overset{k_1}{-\!\!\!-\!\!\!-} \cdots \overset{k_{h-1}}{-\!\!\!-\!\!\!-} t_h$ such that $h \neq 0$ and input ``t`` be an integer between 0 and $h-1$, then return the seed at $t_\mathsf{t}$.

INPUT:
- ``t``-- an integer between 0 and length of trace of ``self``.

In [2]:
B = matrix([
    [0,2,0],
    [-1,0,1],
    [0,-1,0]
])
D = matrix.diagonal([2,1,1])
S = SeedPattern(B, D)

In [5]:
S.mutate(0)
S.mutate(1)
S.mutate(2)

In [6]:
S.trace(0).b_matrix(), S.trace(1).b_matrix(), S.trace(2).b_matrix(), S.b_matrix()

(
[ 0  2  0]  [ 0 -2  0]  [ 0  2  0]  [ 0  2  0]
[-1  0  1]  [ 1  0  1]  [-1  0 -1]  [-1  0  1]
[ 0 -1  0], [ 0 -1  0], [ 0  1  0], [ 0 -1  0]
)

## SignCone
A *sign cone* is a cone of [sign fan](#SignFan), which is consisted by a convex rational polyedral cone with presentation matrix.
In this file, sign cone is given by the inward normal vectors of the cone, presentation matrix $M$ and sign associtated to $M$.

### *class* SignCone(vects, matrix, sign, perm=None)¶
The *sign fan* associated to the input data.

INPUT:
- ``vects`` -- the list of inward normal vectors. (Should not be minimal.)
- ``matrix`` -- the presentation matrix.
- ``sign``-- the list of signs.

### cone()
Return the [Convex rational polyhedral cones](http://doc.sagemath.org/html/en/reference/discrete_geometry/sage/geometry/cone.html?highlight=polyhedral%20cone#module-sage.geometry.cone) associated to ``self``.

### dim()
Return the dimension of the [cone](#cone()) of ``self``.

### is_invariant(f)
Check ``self`` is invariant under the mutation loop ``f``.

INPUT:
- ``f`` -- the mutation loop.

OUTPUT:
- ``True`` if ``f(cone(self))`` is contained in ``cone(self)``, ``False`` otherwise. 

### normal_vectors()
Return the inward normal vectors of facets of ``self``.
(It is not equal to the input datum ``vects``.)

### presentation_matrix()
Return the presentation matirx associtated to ``self``.

### rays()
Return the list of rays of ``cone(self)``.

### show()
Print the rays of ``cone(self)`` and presentation matrix of ``self``.

### sign()
Retrun the list of signs of ``self``.

## SignFan
A *sign fan* is a complete fan on the tropical cluster $\mathcal{X}$-variety corresnponds to a mutation sequence $f$ such that the induced PL map, called tropical cluster $\mathcal{X}$-transformation of $f$ is linear on each cone of the fan.
In this file, a *sign fan* is a collection of [sign cones](#SignCone), especially the corresponding cones form a fan satisfying above condition.
The class *SignFan* is a subclass of [*SeedPattern*](#SeedPattern).

### *class* SignFan(B, seq, perm=None, D=None, mentions=True)
The sign fan of the mutation sequence generated by the given data.

INPUT:
- ``B`` -- a skew symmetrizable matrix.
- ``seq`` -- a list consists of some numbers from 0 to the number of rows of ``B`` -1; it corresponds to the indices to mutate; ``seq[i]`` is the ``i``th index to mutate.
- ``perm`` -- a list consists of numbers from 0 to the number of rows of ``B`` -1; it is corresponds to the permutation of indices; ``perm[i]`` is the image of ``i`` by the permutation.
- ``D`` -- (default: ``None``); if ``B`` is not skew symmetric, it is a symmetrizer of ``B``.
- ``mentions`` -- (default: ``True``);if ``True``, print some mentions; if you are worrywart, we recommend to input as ``True``.

EXAMPLES:

### base_matrix()
Return the $B$-matrix of seed at the time 0.

### dim()
Return the dimension of the fan of ``self``.

### facets()
Return the list of facets (codimension 1 cones) of ``self``.

### n()
Return the number of max dimensional cones of ``self``.

### permutation()
Retrun the perumtation of the mutation sequence of ``self``.

### project(basis)
Return the projected fan into the subspace spaned by ``basis``.

### plot_stereographic_projection(figsize=[4,4], axes=True, color='blue', thickness=1)
Return the 

INPUT:
- ``figsize`` -- (default: ``[4,4]``); the size of figure.
- ``axes`` -- (default: ``True``); if ``True``, drow the axes.
- ``color`` -- (default: ``'blue'``); the color of plots.
- ``thickness`` -- (default: 1); the thickness of arcs of plots.

### sequence()
Return the list of mutating indices corresponds to the mutation sequence of ``self``.

### show()
Print the details of max dimensional sign cones contained in ``self``.

### sign_cones()
Return the list of max dimensional sign cones contained in ``self``.

### sings()
Return the list of list of signs which corresponds to some max dimensional sign cones contained in ``self``.

## MutationLoop
A *mutation loop* is consists of a skew symmetrizable matrix $B$, a sequence of indices $(k_0, k_1, \dots, k_{h-1})$ and a permutation $\sigma$ satisfying the mutated and permutated matrix $\sigma . \mu_{k_{h-1}} \cdots \mu_1 \mu_0 B$ coincides with the original matrix $B$.
This class is a subclass of [SeedPattern](#SeedPattern)

### *class* MutationLoop(B, seq, perm, D=None)
INPUT:
- ``B`` -- the skew symmetrizable matrix.
- ``seq`` -- a list consists of some numbers from 0 to the number of rows of ``B`` -1; it corresponds to the indices to mutate; ``seq[i]`` is the ``i``th index to mutate.
- ``perm`` -- a list consists of numbers from 0 to the number of rows of ``B`` -1; it is corresponds to the permutation of indices; ``perm[i]`` is the image of ``i`` by the permutation; satisfying the above condition.
- ``D`` -- (default: ``None``); if ``B`` is not skew symmetric, it is a symmetrizer of ``B``.

EXAMPLES:

### a_presentation_matrix(sign)
Return the presentation matrix of signed tropical A-transformation associated to the input sign.

INPUT:
- ``sign`` -- a sequence of signs.



###  a_trop_transformation(a)
Return the mutated ``a`` in A^trop, the presentation matrix and the list of signs.

INPUT:
- ``a`` -- a point of A^trop.
    


### base_matrix()
Return the $B$-matrix of seed at the time 0.

### c_matrix()
Retrun the $C$-matrix associated to the last seed of ``self``.

### compose(f, show=True)
         
Return the mutation loop as ``f*self``.

INPUT:
- ``f`` -- a mutation loop with the same [base matrix](#base_matrix()).

### contract()
Remove the sublist like as ``[i,i]`` contained in ``seq`` of ``self``.

EXAMPLES:

In [96]:
B_4_sph = matrix.zero(6)
B_4_sph[0,2]=1
B_4_sph[2,3]=1
B_4_sph[3,1]=1
B_4_sph[1,0]=1
B_4_sph[3,5]=1
B_4_sph[5,0]=1
B_4_sph[0,4]=1
B_4_sph[4,3]=1
B_4_sph = -B_4_sph + B_4_sph.transpose()

In [148]:
f = MutationLoop(B_4_sph, [0,1,2,2,1,4], [4,1,0,2,3,5])

In [149]:
f.contract()

contracted sequence of vertices: [0, 1, 1, 4]


In [153]:
f.trace(3)

In [15]:
f.contract()

contracted sequence of vertices: [0, 4]


In [16]:
f.contract()

contracted sequence of vertices: [0, 4]


### deform(r)
Apply the square (resp. pentagon) move at ``r``th place in ``seq`` of ``self`` when ``self.trace(r).b_matrix()[seq[r], seq[r]]= 0`` (resp. ``=1``).

INPUT:
- ``r`` -- an integer from ``0`` to ``length(self)-1``.

EXAMPLES:

In [108]:
B_4_sph = matrix.zero(6)
B_4_sph[0,2]=1
B_4_sph[2,3]=1
B_4_sph[3,1]=1
B_4_sph[1,0]=1
B_4_sph[3,5]=1
B_4_sph[5,0]=1
B_4_sph[0,4]=1
B_4_sph[4,3]=1
B_4_sph = -B_4_sph + B_4_sph.transpose()

In [158]:
f = MutationLoop(B_4_sph, [0,4], [4,1,0,2,3,5])

In [161]:
f.deform(0)

deformed sequence of vertices: [1, 3, 1]
deformed permutation: [5, 1, 2, 0, 4, 3]


In [160]:
f = MutationLoop(B_4_sph, [3,1], [5,0,2,1,4,3])

### fixed_points_in_x(trace=False)
Return the fixed poins in PX^trop and whose stretch factors.

INPUT:
- ``trace`` -- bool(default ``False``); whether print signs being processed.
    


### g_matrix()
    
Retrun the $G$-matrix associated to the last seed of ``self``.

### length()
Return the length of list ``seq`` of indices of ``self``.

### perm_matrix()
Retrun the presentation matrix of the permutation ``perm`` of ``self``.

### inverse()
Return the mutation loop which is the inverse of ``self``.

### iterate(m, show=True)
Return the mutation loop which is the iterated ``self``.

INPUT:
- ``m`` -- a positive integer; the output is ``self^m``.

### invariant_cones(M, show=True, mentions=True)
Return the invariant cones in the sign fan of ``self``.

INPUT:
- ``M`` -- a positive integer; check for ``self.iterate(M)``.

### is_equivalent_to(f)
Check ``self`` is equivalent to ``f``.

INPUT:
- ``f`` -- a mutation loop with same [base matrix](#base_matrix()).

### is_sign_stable(rays, M=5, m=50, lim_cone=False, mentions=True)
        


### is_basic_sign_stable(M=5, m=50)

### iterated_trial_in_a(a, m, trace=False, err=10^-4)
This method is an itarated trial in PA^trop.
If 'a' is converging to a point, then return the sign at the point.

INPUT:
- ``a`` -- a point in A^trop
- ``m`` -- a number of times to hit
- ``trace`` -- bool(default: ``False``); whether print coordinates and signs during ``a`` is wandering
- ``err`` -- arrowable error (default: 10^-4)
    


### iterated_trial_in_x(x, m=100, trace=False, err=10^-4)
This method is an itarated trial in PX^trop.
If 'x' is converging to a point, then return the sign at the point.

INPUT:
- ``x`` -- a point in X^trop
- ``m`` -- (default: 100) a number of times to hit
- ``trace`` -- bool(default: ``False``); whether print coordinates and signs during ``x`` is wandering
- ``err`` -- arrowable error (default: 10^-4)
        


### show()
        


### sign_fan(mentions=True)



### trop_sign()
    


### x_presentation_matrix(sign)
Return the presentation matrix of signed tropical X-transformation associated to the input sign.

INPUT:
- ``sign`` -- a sequence of signs.
        


### x_trop_transformation(x)
Return the mutated ``x`` in X^trop, the presentation matrix and the list signs.
        
INPUT:
- ``x`` -- a point of X^trop.

EXAMPLES:

