# Cluster modular groups
This is a manual of [cluster_modular_group.sage](https://github.com/kmtm0723/ClusterModularGroup).

A *cluster modular group* is a symmetry group of a *cluster algebra*, which is generated by *mutation loops*.

AUTHOR:
- Shunsuke Kano

REFERENCES:
- [[IK19]](https://arxiv.org/abs/1911.07587)

To use this file, you have to load it first:

In [1]:
load('cluster_modular_group.sage')

This file consists of following classes:

- [**SeedPattern**](#SeedPattern)
- [**SignCone**](#SignCone)
- [**SignFan**](#SignFan)
- [**MutationLoop**](#MutationLoop)

We note that the classes SignFan and MutationLoop are the subclass of the class SeedPattern.

Maybe you will use [MutationLoop](#MutationLoop) mainly, so we recommend to read the usage of it first.

## SeedPattern
A *seed pattern* is an assignment of *seed datum* on each vertex of a given regular tree $\mathbb{T}_N$ such that each adjacent seed data are related by *mutation*.

In this file, the seed pattern is a restricted assignment to a edge path in the regular tree.
That is, for a vertex $t_0 \in \mathbb{T}_N$, we assign a seed datum associated to a given exchange matrix $B_0$.
If next we [mutate](#mutate(k)) at $k_0$ this seed datum, then we assign a new seed datum associated to a mutated exchange matrix $\mu_{k_0}B_0$ to a adjucent vertex $t_1$.
When iterate $h$ times this process, we finally obtain the seed assginment for an edge path $t_0 \overset{k_0}{-\!\!\!-\!\!\!-} t_1 \overset{k_1}{-\!\!\!-\!\!\!-} \cdots \overset{k_{h-1}}{-\!\!\!-\!\!\!-} t_h$.

The class object of SeedPattern storage the exchange matrix assigned to the ending vertex of the edge path and seeds assigned to other vertices as a [*trace*](#trace(t)) of it.
Namely, the mutated object is the seed 

### *class*  SeedPattern(B, D=None)

The *seed pattern* associated to an *exchange matrix*.

INPUT:
- ``B`` -- a skew-symmetric or skew-symmetrizable matrix.
- ``D`` -- (default: ``None``); a symmetrizer of ``B``; a diagonal matrix with positive integers such that ``B*D`` is skew-symmetric.

EXAMPLES:

In [2]:
B = matrix([
    [0,2],
    [-1,0]
])
D = matrix.diagonal([2,1])
S = SeedPattern(B, D)
S

In [3]:
B_4_sph = matrix.zero(6)
B_4_sph[0,2]=1
B_4_sph[2,3]=1
B_4_sph[3,1]=1
B_4_sph[1,0]=1
B_4_sph[3,5]=1
B_4_sph[5,0]=1
B_4_sph[0,4]=1
B_4_sph[4,3]=1
B_4_sph = -B_4_sph + B_4_sph.transpose()
B_4_sph
S_4_sph = SeedPattern(B_4_sph)
S_4_sph.b_matrix()

[ 0  1 -1  0 -1  1]
[-1  0  0  1  0  0]
[ 1  0  0 -1  0  0]
[ 0 -1  1  0  1 -1]
[ 1  0  0 -1  0  0]
[-1  0  0  1  0  0]

In [4]:
S_4_sph.mutate(0)
S_4_sph.b_matrix()

[ 0 -1  1  0  1 -1]
[ 1  0 -1  1 -1  0]
[-1  1  0 -1  0  1]
[ 0 -1  1  0  1 -1]
[-1  1  0 -1  0  1]
[ 1  0 -1  1 -1  0]

In [5]:
S_4_sph.trace(0).b_matrix() == B_4_sph

True

### b_matrix()
Retrun the copy of the exchange matrix of a seed assigned to ending vertex of ``self``.

EXAMPLES:

In [6]:
B_4_sph = matrix.zero(6)
B_4_sph[0,2]=1
B_4_sph[2,3]=1
B_4_sph[3,1]=1
B_4_sph[1,0]=1
B_4_sph[3,5]=1
B_4_sph[5,0]=1
B_4_sph[0,4]=1
B_4_sph[4,3]=1
B_4_sph = -B_4_sph + B_4_sph.transpose()
B_4_sph
S_4_sph = SeedPattern(B_4_sph)

In [7]:
S_4_sph.b_matrix()

[ 0  1 -1  0 -1  1]
[-1  0  0  1  0  0]
[ 1  0  0 -1  0  0]
[ 0 -1  1  0  1 -1]
[ 1  0  0 -1  0  0]
[-1  0  0  1  0  0]

In [8]:
S_4_sph.mutate(0)
S_4_sph.b_matrix()

[ 0 -1  1  0  1 -1]
[ 1  0 -1  1 -1  0]
[-1  1  0 -1  0  1]
[ 0 -1  1  0  1 -1]
[-1  1  0 -1  0  1]
[ 1  0 -1  1 -1  0]

### E(k, e, t=-1)
Return the presentation matrix of dual seed mutation in a direction toward ``k`` of sign = ``e`` at ``t``.

INPUT:
- ``k`` -- a direction of mutation.
- ``e`` -- a sign of a seed mutation.
- ``t`` -- (default -1); if -1, return the presentation matrix at ``self``, otherwise at ``self.trace(t)``.

EXAMPLES:

In [9]:
B = matrix([
    [0,2],
    [-1,0]
])
D = matrix.diagonal([2,1])
S = SeedPattern(B, D)

In [10]:
S.mutate(0)
S.mutate(1)

In [11]:
S.E(0, 1)

[-1  0]
[ 0  1]

In [12]:
S.E(0, 1, t=1)

[-1  0]
[ 2  1]

### E_check(k, e, t=-1)
Return the presentation matrix of seed mutation in a direction toward ``k`` of sign = ``e`` at ``t``.

INPUT:
- ``k`` -- a direction of the mutation.
- ``e`` -- a sign of a seed mutation.
- ``t`` -- (default -1); if -1, return the presentation matrix at ``self``, otherwise return the presentation matrix at ``self.trace(t)``.

EXAMPLES:

In [13]:
B = matrix([
    [0,2,0],
    [-1,0,1],
    [0,-1,0]
])
D = matrix.diagonal([2,1,1])
S = SeedPattern(B, D)

In [14]:
S.mutate(0)
S.mutate(2)

In [15]:
S.E_check(1, -1)

[ 1  0  0]
[ 2 -1  0]
[ 0  0  1]

In [16]:
S.E_check(1, -1, t=0)

[ 1  0  0]
[ 0 -1  1]
[ 0  0  1]

### mutate(k)
Storage the copy of ``self`` to its trace and mutate ``self`` in a direction toward ``k``.

INPUT:
- ``k`` -- a direction of the mutation.

EXAMPLES:

In [17]:
B = matrix([
    [0,3],
    [-1,0]
])
D = matrix.diagonal([3,1])
S = SeedPattern(B, D)

In [18]:
S.mutate(1)
S.mutate(0)
S.mutate(1)

In [19]:
S.trace(0).b_matrix(), S.trace(1).b_matrix(), S.trace(2).b_matrix(), S.b_matrix()

(
[ 0  3]  [ 0 -3]  [ 0  3]  [ 0 -3]
[-1  0], [ 1  0], [-1  0], [ 1  0]
)

### rank()
Return the size of the index set of ``self``.

EXAMPLES:

In [20]:
B = matrix([
    [0,2],
    [-1,0]
])
D = matrix.diagonal([2,1])
S = SeedPattern(B, D)

In [21]:
S.rank()

2

In [22]:
B = matrix([
    [0,2,0],
    [-1,0,1],
    [0,-1,0]
])
D = matrix.diagonal([2,1,1])
S = SeedPattern(B, D)

In [23]:
S.rank()

3

### trace(t)
If ``self`` is the seed pattern on the path $t_0 \overset{k_0}{-\!\!\!-\!\!\!-} t_1 \overset{k_1}{-\!\!\!-\!\!\!-} \cdots \overset{k_{h-1}}{-\!\!\!-\!\!\!-} t_h$ such that $h \neq 0$ and input ``t`` be an integer between 0 and $h-1$, then return the seed at $t_\mathsf{t}$.

INPUT:
- ``t``-- an integer between 0 and length of trace of ``self``.

## SignCone



### class SignCone(vects, matrix, sign, perm=None)¶

### codim()

### cone()

### dim()

### is_invariant(f)
    
### normal_vectors()

### presentation_matrix()

### rays()
    
### show()

### sign()

## SignFan

### base_matrix()

### sequence()

### permutation()

### sign_cones()
    
### dim()

### n()
    
### facets()
    
### show()
            
### sings()

### project(basis)
Return the projected fan into the subspace spaned by 'basis'.

### plot_stereographic_projection(figsize=[4,4], axes=True, color='blue', thickness=1, gradation=False)

## MutationLoop

### base_matrix()
            
### show()
        
### length()
    
### perm_matrix()
    
### inverse()
    
### compose(f, show=True)
         
### iterate(m, show=True)
    
### contract()
    
### deform(r)
    
### x_trop_transformation(x)
Return the mutated ``x`` in X^trop, the presentation matrix and the list signs.
        
INPUT:
- ``x`` -- a point of X^trop.

EXAMPLES:

###  a_trop_transformation(a)
Return the mutated ``a`` in A^trop, the presentation matrix and the list of signs.

INPUT:
- ``a`` -- a point of A^trop.
    
### x_presentation_matrix(sign)
Return the presentation matrix of signed tropical X-transformation associated to the input sign.

INPUT:
- ``sign`` -- a sequence of signs.
        
### a_presentation_matrix(sign)
Return the presentation matrix of signed tropical A-transformation associated to the input sign.

INPUT:
- ``sign`` -- a sequence of signs.

### sign_fan(mentions=True)

### fixed_points_in_x(trace=False)
Return the fixed poins in PX^trop and whose stretch factors.

INPUT:
- ``trace`` -- bool(default ``False``); whether print signs being processed.
    
### invariant_cones(M, show=True, mentions=True)
    
### itarated_trial_in_x(x, m=100, trace=False, err=10^-4)
This method is an itarated trial in PX^trop.
If 'x' is converging to a point, then return the sign at the point.

INPUT:
- ``x`` -- a point in X^trop
- ``m`` -- (default: 100) a number of times to hit
- ``trace`` -- bool(default: ``False``); whether print coordinates and signs during ``x`` is wandering
- ``err`` -- arrowable error (default: 10^-4)
        
### itarated_trial_in_a(a, m, trace=False, err=10^-4)
This method is an itarated trial in PA^trop.
If 'a' is converging to a point, then return the sign at the point.

INPUT:
- ``a`` -- a point in A^trop
- ``m`` -- a number of times to hit
- ``trace`` -- bool(default: ``False``); whether print coordinates and signs during ``a`` is wandering
- ``err`` -- arrowable error (default: 10^-4)
    
### c_matrix()

### g_matrix()
    
### trop_sign()
    
### is_equivalent_to(f)

### is_sign_stable(rays, M=5, m=50, lim_cone=False, mentions=True)
        
### is_basic_sign_stable(M=5, m=50)